# Generated by Django 6.0.3 on 2026-03-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipe_name', models.CharField(max_length=100)),
                ('receipe_Description', models.TextField()),
                ('receipe_image', models.ImageField(upload_to='receipe_images/')),
            ],
        ),
    ]
