# Generated by Django 6.0.3 on 2026-03-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipe', '0003_department_employee_id_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_phone',
            field=models.CharField(max_length=100),
        ),
    ]
